# Generated by Django 5.1 on 2024-09-04 05:43

import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "variant_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        length=6,
                        max_length=6,
                        prefix="",
                        unique=True,
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariantItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("file", models.FileField(upload_to="course-file")),
                (
                    "variant_item_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        length=6,
                        max_length=30,
                        prefix="",
                        unique=True,
                    ),
                ),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "content_duration",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("preview", models.BooleanField(default=False)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_items",
                        to="api.variant",
                    ),
                ),
            ],
        ),
    ]
