# Generated by Django 5.1 on 2024-09-20 08:23

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_cartorderitem_price_alter_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrolledcourse",
            name="enrolled_id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="1234567890", length=6, max_length=20, prefix="", unique=True
            ),
        ),
    ]
