# Generated by Django 5.1 on 2024-08-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="opt",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
