<<<<<<< HEAD:backend/apps/account/migrations/0005_rename_opt_user_otp.py
# Generated by Django 5.1 on 2024-12-18 19:23
=======
# Generated by Django 5.1 on 2024-12-19 11:20
>>>>>>> ceb4b3d8 (changing password and generated otp):backend/account/migrations/0005_rename_opt_user_otp.py

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="opt",
            new_name="otp",
        ),
    ]
