# Generated by Django 5.1 on 2024-12-18 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="opt",
            new_name="otp",
        ),
    ]
