# Generated by Django 5.1 on 2024-08-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_opt"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
