# Generated by Django 5.1 on 2024-09-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_cart_cart_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("New Order", "New Order"),
                    ("New Review", "New Review"),
                    ("New Course Question", "New Course Question"),
                    ("Draft", "Draft"),
                    ("Course Enrollment Completed", "Course Enrollment Completed"),
                ],
                max_length=100,
            ),
        ),
    ]
