# Generated by Django 5.1 on 2024-12-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_rename_teachers_cartorder_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantitem",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="course-file"),
        ),
    ]
